version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  app_0:
    build: .
    image: socialbackend
    container_name: app_0
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      DB_CONTAINER_NAME: mongodb
      CACHE_CONTAINER_NAME: redis
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
  app_1:
    image: socialbackend
    container_name: app_1
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      DB_CONTAINER_NAME: mongodb
      CACHE_CONTAINER_NAME: redis
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
  app_2:
    image: socialbackend
    container_name: app_2
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      DB_CONTAINER_NAME: mongodb
      CACHE_CONTAINER_NAME: redis
    ports:
      - "3002:3000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_0
      - app_1
      - app_2
volumes:
  mongodb_data:
